pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = sh(script: 'aws configure get aws_access_key_id', returnStdout: true).trim()
        AWS_SECRET_ACCESS_KEY = sh(script: 'aws configure get aws_secret_access_key', returnStdout: true).trim()
    }

    stages {
        stage('Plan') {
            steps {
                script {
                    sh 'terraform init'
                    sh 'terraform plan -out=tfplan'
                }
            }
        }

        stage('Apply') {
            steps {
                script {
                    def userInput = input(
                        id: 'userInput',
                        message: 'Do you want to apply the plan? (Yes/No)',
                        parameters: [choice(name: 'choice', choices: 'Yes\nNo', description: '')]
                    )
                    
                    if (userInput == 'Yes') {
                        sh 'terraform apply tfplan'
                    } else {
                        echo 'Skipping apply stage'
                    }
                }
            }
        }

        stage('Destroy') {
            steps {
                script {
                    def userInput = input(
                        id: 'userInput',
                        message: 'Do you want to destroy the resource? (Yes/No)',
                        parameters: [choice(name: 'choice', choices: 'Yes\nNo', description: '')]
                    )
                    
                    if (userInput == 'Yes') {
                        sh 'terraform destroy'
                    } else {
                        echo 'Skipping destroy stage'
                    }
                }
            }
        }
    }
}
